# Generated by Django 4.1.3 on 2022-11-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polcom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polcom',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('done', 'DONE')], default='pending', max_length=7),
            preserve_default=False,
        ),
    ]
