# Generated by Django 4.1.3 on 2022-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polcom', '0002_polcom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polcom',
            name='principal',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
    ]
