# Generated by Django 4.1.3 on 2022-11-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricom', '0002_agricom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agricom',
            name='principal',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='agricom',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('done', 'DONE')], default='no', max_length=7),
            preserve_default=False,
        ),
    ]
