# Generated by Django 4.1.3 on 2022-11-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtask',
            options={'ordering': ('completed', '-created'), 'verbose_name': 'BlogTasks'},
        ),
    ]
